### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by aobase-noodle** [svga/SVGAPlayer-Android#122]
RuntimeEnumAdapterd 中调用了getFromValueMethod，　反射 fromValue
在我们项目中，对应的调用了　ShapeEntity.ShapeStyle.LineJoin　的fromValue(int)  
但是没有看到文档有这个混淆需要添加

**Comment by aobase-noodle** [comment]
```
java.lang.AssertionError: java.lang.NoSuchMethodException: fromValue [int]
        at com.squareup.wire.RuntimeEnumAdapter.c(SourceFile:41)
        at com.squareup.wire.RuntimeEnumAdapter.a(SourceFile:49)
        at com.squareup.wire.EnumAdapter.a(SourceFile:38)
        at com.squareup.wire.EnumAdapter.b(SourceFile:23)
        at com.opensource.svgaplayer.proto.ShapeEntity$ProtoAdapter_ShapeEntity.a(SourceFile:1469)
        at com.opensource.svgaplayer.proto.ShapeEntity$ProtoAdapter_ShapeEntity.b(SourceFile:1434)
        at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.a(SourceFile:237)
        at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.b(SourceFile:202)
        at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.a(SourceFile:153)
        at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.b(SourceFile:127)
        at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.a(SourceFile:242)
        at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.b(SourceFile:206)
        at com.squareup.wire.ProtoAdapter.a(SourceFile:203)
        at com.squareup.wire.ProtoAdapter.a(SourceFile:185)
        at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SourceFile:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoSuchMethodException: fromValue [int]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.squareup.wire.RuntimeEnumAdapter.c(SourceFile:39)
        at com.squareup.wire.RuntimeEnumAdapter.a(SourceFile:49) 
        at com.squareup.wire.EnumAdapter.a(SourceFile:38) 
        at com.squareup.wire.EnumAdapter.b(SourceFile:23) 
        at com.opensource.svgaplayer.proto.ShapeEntity$ProtoAdapter_ShapeEntity.a(SourceFile:1469) 
        at com.opensource.svgaplayer.proto.ShapeEntity$ProtoAdapter_ShapeEntity.b(SourceFile:1434) 
        at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.a(SourceFile:237) 
        at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.b(SourceFile:202) 
        at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.a(SourceFile:153) 
        at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.b(SourceFile:127) 
        at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.a(SourceFile:242) 
        at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.b(SourceFile:206) 
        at com.squareup.wire.ProtoAdapter.a(SourceFile:203) 
        at com.squareup.wire.ProtoAdapter.a(SourceFile:185) 
        at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SourceFile:129) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
```

**Comment by PonyCui** [comment]
应该是 wire 要求的规则，请添加以下规则。

-keep class com.squareup.wire.** { *; }
-keep class com.opensource.svgaplayer.proto.** { *; }
