### ISSUE TITLE
Failed to allocate a 1000512 byte allocation with 449120 free bytes and 438KB until OOM

### ISSUE THREAD

**Issue by suiyuanchen** [svga/SVGAPlayer-Android#124]
java.lang.OutOfMemoryError: Failed to allocate a 1000512 byte allocation with 449120 free bytes and 438KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
        at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:561)
        at com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:112)
        at com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.kt:67)
        at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android/issues/98

**Comment by suiyuanchen** [comment]
是否还有其他的优化空间呢？或者好的方法，策略，思路？或者有没有手动释放内存的接口？

**Comment by PonyCui** [comment]
先找设计师优化

**Comment by suiyuanchen** [comment]
> #98
是否还有其他的优化空间呢？或者好的方法，策略，思路？或者有没有手动释放内存的接口？大图片大小一般最大多大为好

**Comment by PonyCui** [comment]
你这种动画一般就是直接用序列帧做的，肯定爆内存。
