### ISSUE TITLE
SVGA 出现OOM

### ISSUE THREAD

**Issue by HalyangDream** [svga/SVGAPlayer-Android#145]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)
在友盟统计上，在最新发布的一个版本，我们使用SVGA超过700人的设备出现OOM，出现次数搭4500
出现问题的设备
 Nile X            7.0
SM-J701F      8.1.0
SM-J200F     5.1.1
How To Reappear(How to reappear the issue)
不断的使用SVGA动画
Any Attachment(Provide a sample about your issue)
java.lang.OutOfMemoryError: Failed to allocate a 21341 byte allocation with 9080 free bytes and 8KB until OOM
	at java.lang.Object.internalClone(Native Method)
	at java.lang.Object.clone(Object.java:229)
	at okio.ByteString.toByteArray(ByteString.java:354)
	at com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:105)
	at com.opensource.svgaplayer.SVGAVideoEntity.&lt;init&gt;(SVGAVideoEntity.kt:67)
	at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by PonyCui** [comment]
先咨询一下设计师，看看导出时候提示的内存占用有多大。

**Comment by HalyangDream** [comment]
> 看看导出时候提示的内存占用有多大
最大的大约在2M左右

**Comment by PonyCui** [comment]
是指文件 2M 还是内存占用 2M

**Comment by HalyangDream** [comment]
> 是指文件 2M 还是内存占用 2M

文件2M

**Comment by PonyCui** [comment]
十成是因为你的动画是使用序列帧的，让设计师重做导出。

**Comment by donadoo** [comment]
> 十成是因为你的动画是使用序列帧的，让设计师重做导出。

应该是用关键帧来做动画吗？
