### ISSUE TITLE
Use decodeFromFile(file.callback)  error.

### ISSUE THREAD

**Issue by 291700351** [svga/SVGAPlayer-Android#150]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)
Use decodeFromFile(file.callback)  error.
This is error message:
 java.io.IOException: Stream Closed
        at java.io.FileInputStream.read(FileInputStream.java:251)
        at com.opensource.svgaplayer.SVGAParser.readAsBytes(SVGAParser.kt:248)
        at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:113)
        at com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:23)
        at com.opensource.svgaplayer.SVGAParser$parse$5.run(SVGAParser.kt:96)
        at java.lang.Thread.run(Thread.java:764)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by errnull** [comment]
could you provide an example?
@291700351

**Comment by errnull** [comment]
Reply timed out
