### ISSUE TITLE
OOM Bugs Again

### ISSUE THREAD

**Issue by CensorKo** [svga/SVGAPlayer-Android#152]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 562512 byte allocation with 248816 free bytes and 242KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeByteArray(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:561)
       at com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.java:112)
       at com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.java:112)
       at com.opensource.svgaplayer.SVGAVideoEntity.(SVGAVideoEntity.kt:67)
       at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.java:129)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by 1290846731** [comment]
规范设计出的动画

**Comment by errnull** [comment]
设计师插件输出动效的时候会提示动效资源内存占用，
如果超过阈值会提示低端设备可能奔溃，
出现这个问题一般是设计师动效不规范导致的。
