### ISSUE TITLE
java.util.zip.DataFormatException: incorrect header check

### ISSUE THREAD

**Issue by smallwhitexujian** [svga/SVGAPlayer-Android#169]
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err: java.util.zip.DataFormatException: incorrect header check
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at java.util.zip.Inflater.inflateBytes(Native Method)
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at java.util.zip.Inflater.inflate(Inflater.java:260)
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at com.opensource.svgaplayer.SVGAParser.inflate(SVGAParser.kt:272)
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at com.opensource.svgaplayer.SVGAParser.access$inflate(SVGAParser.kt:23)
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:132)
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-07-04 18:00:26.846 10630-15881/com.example.ponycui_home.svgaplayer W/System.err:     at java.lang.Thread.run(Thread.java:760)

**Comment by smallwhitexujian** [comment]
http://hw.static.djdl2009.com/201927/15621399564c17bb.svga 这个地址可以试试？解析不出来

**Comment by haegyeong** [comment]
请问这个异常，你是怎么解决的

**Comment by sichuanyl** [comment]
用https

**Comment by daishengda2018** [comment]
这个是内部解压工具（Inflate） 校验数据头的错误，你们外加了什么压缩方式吗？或者你们修改了源码读了流但没有移动指针回文件头？

**Comment by star-heng** [comment]
什么压缩方式？

>

**Comment by star-heng** [comment]
> 这个是内部解压工具（Inflate） 校验数据头的错误，你们外加了什么压缩方式吗？或者你们修改了源码读了流但没有移动指针回文件头？

什么压缩方式？源码没修改
现在用的是2.6.1

https://h5.hengkang.life/img/comphm.svga这个地址也出现上面的问题

**Comment by ifynn** [comment]
请问这个有结果吗？我也出现了
