### ISSUE TITLE
线程创建崩溃

### ISSUE THREAD

**Issue by drumge** [svga/SVGAPlayer-Android#171]
线程创建崩溃，建议提供接口业务方设置线程池
```java
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:733)
	at com.opensource.svgaplayer.f.a(SVGAParser.kt:122)
```

**Comment by drumge** [comment]
```kotlin
open fun resume(url: URL, complete: (inputStream: InputStream) -> Unit, failure: (e: Exception) -> Unit): () -> Unit {
            var cancelled = false
            val cancelBlock = {
                cancelled = true
            }
            Thread {
                try {
                    if (HttpResponseCache.getInstalled() == null && !noCache) {
                        Log.e("SVGAParser", "SVGAParser can not handle cache before install HttpResponseCache. see https://github.com/yyued/SVGAPlayer-Android#cache")
                        Log.e("SVGAParser", "在配置 HttpResponseCache 前 SVGAParser 无法缓存. 查看 https://github.com/yyued/SVGAPlayer-Android#cache ")
                    }
                    (url.openConnection() as? HttpURLConnection)?.let {
                        it.connectTimeout = 20 * 1000
                        it.requestMethod = "GET"
                        it.connect()
                        it.inputStream.use { inputStream ->
                            ByteArrayOutputStream().use { outputStream ->
                                val buffer = ByteArray(4096)
                                var count: Int
                                while (true) {
                                    if (cancelled) {
                                        break
                                    }
                                    count = inputStream.read(buffer, 0, 4096)
                                    if (count == -1) {
                                        break
                                    }
                                    outputStream.write(buffer, 0, count)
                                }
                                if (cancelled) {
                                    return@Thread
                                }
                                ByteArrayInputStream(outputStream.toByteArray()).use {
                                    complete(it)
                                }
                            }
                        }
                    }
                } catch (e: Exception) {
                    e.printStackTrace()
                    failure(e)
                }
            }.start()
            return cancelBlock
        }
```
请教一下，SVGAParser#FileDownloader 类中的这个方法是出于什么考虑不用线程池反而每次都创建一个线程呢

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-Android/pull/142
另外，你可以自定义 downloader。

**Comment by errnull** [comment]
使用 Parser 的 `setFileDownloader()`
确实可以自定下载方法。

**Comment by drumge** [comment]
总共有三个地方使用了 thread，建议都改成使用线程池

**Comment by jhyHenry** [comment]
建议FileDownloader里thread改为Executors.newSingleThreadExecutor()好点，就算是提供了setFileDownloader（）给业务方自定义，默认的实现也应该考虑OOM的情况

**Comment by PonyCui** [comment]
这里确实可以修改一下

**Comment by jhyHenry** [comment]
我看你新的代码线程池已经改为静态变量了，但是好像没发新版本，可以和这个一起修改下然后发个新版本么，我们这边发现OOM比较严重

**Comment by PonyCui** [comment]
The master branch, and tag 2.4.7 release fixed.
