### ISSUE TITLE
drawTextOnBitmap 部分特殊文字会出现IndexOutOfBoundsException 必现

### ISSUE THREAD

**Issue by lic2050** [svga/SVGAPlayer-Android#185]
绘制部分特殊文字会导致IndexOutOfBoundsException  必现
有个用户的昵称是:  Super Hossam ,♚ʟ
在svga动画中绘制这个昵称时，会出现崩溃。

目前这个错误已经是应用中错误次数最多的了

java.lang.IndexOutOfBoundsException
    at android.graphics.Paint.getTextBounds(Paint.java:2434)
    at com.opensource.svgaplayer.drawer.SVGACanvasDrawer.drawTextOnBitmap(SVGACanvasDrawer.kt)
    at com.opensource.svgaplayer.drawer.SVGACanvasDrawer.drawImage(SVGACanvasDrawer.kt)
    at com.opensource.svgaplayer.drawer.SVGACanvasDrawer.drawSprite(SVGACanvasDrawer.kt)
    at com.opensource.svgaplayer.drawer.SVGACanvasDrawer.drawFrame(SVGACanvasDrawer.kt)
    at com.opensource.svgaplayer.SVGADrawable.draw(SVGADrawable.kt)
    at android.widget.ImageView.onDraw(ImageView.java:1292)
    at android.view.View.draw(View.java:17250)
    at android.view.View.updateDisplayListIfDirty(View.java:16215)
    at android.view.View.draw(View.java:17016)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
    at android.view.View.draw(View.java:17253)
    at android.view.View.updateDisplayListIfDirty(View.java:16215)
    at android.view.View.draw(View.java:17016)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
    at android.view.View.updateDisplayListIfDirty(View.java:16210)
    at android.view.View.draw(View.java:17016)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
    at android.view.View.updateDisplayListIfDirty(View.java:16210)
    at android.view.View.draw(View.java:17016)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
    at android.view.View.updateDisplayListIfDirty(View.java:16210)
    at android.view.View.draw(View.java:17016)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
    at android.view.View.draw(View.java:17253)
    at com.android.internal.policy.DecorView.draw(DecorView.java:801)
    at android.view.View.updateDisplayListIfDirty(View.java:16215)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:677)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:683)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:797)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2997)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2791)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2382)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6774)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
    at android.view.Choreographer.doCallbacks(Choreographer.java:735)
    at android.view.Choreographer.doFrame(Choreographer.java:667)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
    at android.os.Handler.handleCallback(Handler.java:761)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by PonyCui** [comment]
有没有对应的设备以及系统版本信息？

**Comment by lic2050** [comment]
目前我手上的几台手机都有这个问题：
Honor 10 Lite Android9.0 
华为p10 Android9.0
三星Galaxy on7  Android8.0
三星Galaxy s8+ Android9.0

**Comment by errnull** [comment]
getTextBounds 中确实有 throw IndexOutOfBoundsException 没有处理会导致 Crash。
SVGACanvasDrawer 中使用 getTextBounds 目的是为了获取文本宽度计算居中参数。
直接使用居中文本的绘制方案，
可以避免使用可能 throw error 的方法，
顺便让文本水平也居中。

**Comment by errnull** [comment]
v2.5.3 中修复此问题
