### ISSUE TITLE
#602 java.lang.OutOfMemoryError Failed to allocate a 180012 byte allocation with 46326 free bytes and 45KB until OOM

### ISSUE THREAD

**Issue by xuantiandaozun** [svga/SVGAPlayer-Android#189]
#602 java.lang.OutOfMemoryError
Failed to allocate a 180012 byte allocation with 46326 free bytes and 45KB until OOM

是大概播放的20-30 分钟之后出现这个异常

**Comment by xuantiandaozun** [comment]
svga 循环播放后出现的异常  一边来说要使用20-30分钟之后才会出现

**Comment by imtianx** [comment]
遇到同样的问题，

```
java.lang.OutOfMemoryError: Failed to allocate a 375012 byte allocation with 155186 free bytes and 151KB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
    at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:543)
    at com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:88)
    at com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.kt:57)
    at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:182)
    at com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:25)
    at com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:95)
    at com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:25)
    at com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.kt:61)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by errnull** [comment]
你好，可以将相关 .svga 发送到 help@svga.io 吗？
这边查看了相关 demo 会及时回复。
@imtianx @xuantiandaozun @yangyang10 @lylylywww

**Comment by errnull** [comment]
issue merge #175
