### ISSUE TITLE
wifi网络下可能出现svga下载不下来的问题

### ISSUE THREAD

**Issue by 1wayticket** [svga/SVGAPlayer-Android#255]
svga version:2.5.3
wifi网络下执行播放的时候下载出错导致播放不出来,数据流量是可以的.
有时间帮忙看下.
```
2020-05-25 11:29:43.981 W/System.err: javax.net.ssl.SSLException: Read error: ssl=0xeb34baf8: I/O error during system call, Software caused connection abort
2020-05-25 11:29:43.982 W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
2020-05-25 11:29:43.982 W/System.err:     at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
2020-05-25 11:29:43.982 W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
2020-05-25 11:29:43.983 W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
2020-05-25 11:29:43.983 W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
2020-05-25 11:29:43.989 W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
2020-05-25 11:29:43.989 W/System.err:     at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
2020-05-25 11:29:43.990 W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
2020-05-25 11:29:43.991 W/System.err:     at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:792)
2020-05-25 11:29:43.993 W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
2020-05-25 11:29:43.993 W/System.err:     at com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.kt:59)
2020-05-25 11:29:43.993 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-05-25 11:29:43.993 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-05-25 11:29:43.994 W/System.err:     at java.lang.Thread.run(Thread.java:929)
```

**Comment by Adaclass** [comment]
炫酷吊炸天
