### ISSUE TITLE
4.x 闪退

### ISSUE THREAD

**Issue by imtianx** [svga/SVGAPlayer-Android#267]
```
android.view.InflateException: Binary XML file line #388: Error inflating class com.opensource.svgaplayer.SVGAImageView


Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at android.view.LayoutInflater.createView(LayoutInflater.java:614)
    ... 59 more
Caused by: java.lang.NoSuchMethodError: android.widget.ImageView.<init>
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:23)
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:22)
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt)
    ... 62 more
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at android.view.LayoutInflater.createView(LayoutInflater.java:614)

Caused by: java.lang.NoSuchMethodError: android.widget.ImageView.<init>
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:23)
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:22)
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt)
    ... 62 more
java.lang.NoSuchMethodError: android.widget.ImageView.<init>
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:23)
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:22)
    at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt)
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at android.view.LayoutInflater.createView(LayoutInflater.java:614)
```

4.x 设备会出现以问题。

**Comment by daishengda2018** [comment]
你是使用了 2.5.5 版本吗？这个问题已经在 2.5.6 中修复了，请升级尝试一下。

**Comment by imtianx** [comment]
昨天下午换的 2.5.5 版本，我等下换一个试试。
