### ISSUE TITLE
AndroidRuntime: at com.squareup.wire.ProtoReader.nextTag(ProtoReader.java:143)

### ISSUE THREAD

**Issue by kkmike999** [svga/SVGAPlayer-Android#273]
```
07-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
--
9707-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
9807-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
9907-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
10007-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.squareup.wire.ProtoReader.nextTag(ProtoReader.java:143)
10107-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:237)
10207-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:206)
10307-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:203)
10407-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:185)
10507-22 23:43:07.749 19087 23989 E AndroidRuntime: at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:145)
10607-22 23:43:07.749 19087 23989 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10707-22 23:43:07.749 19087 23989 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10807-22 23:43:07.749 19087 23989 E AndroidRuntime: at java.lang.Thread.run(Thread.java:764)
10907-22 23:43:07.857 19087 19097 E System : Uncaught exception thrown by finalizer
11007-22 23:43:07.857 19087 19097 E System : java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.HashMap.clear()' on a null object reference
11107-22 23:43:07.857 19087 19097 E System : at com.opensource.svgaplayer.SVGAVideoEntity.finalize(SVGAVideoEntity.kt:28)
11207-22 23:43:07.857 19087 19097 E System : at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:254)
11307-22 23:43:07.857 19087 19097 E System : at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:241)
11407-22 23:43:07.857 19087 19097 E System : at java.lang.Daemons$Daemon.run(Daemons.java:107)
```

**Comment by daishengda2018** [comment]
看起来是老版本 SVGAVideoEntity 在 finalize 时做操作导致的问题，这个逻辑在 2.5.5 版本中移除了，请升级到最先版本：2.5.6

**Comment by kkmike999** [comment]
> 看起来是老版本 SVGAVideoEntity 在 finalize 时做操作导致的问题，这个逻辑在 2.5.5 版本中移除了，请升级到最先版本：2.5.6

这应该只是表象。更深层原因是`skipGroup`死循环，或者内存不足导致，可能是资源问题

**Comment by kkmike999** [comment]
先放2.5.3的源码：
```
class SVGAParser(context: Context?) {
fun decodeFromInputStream(inputStream: InputStream, cacheKey: String, callback: ParseCompletion?, closeInputStream: Boolean = false) {
        threadPoolExecutor.execute {
            try {
                readAsBytes(inputStream)?.let { bytes ->
                    if (bytes.size > 4 && bytes[0].toInt() == 80 && bytes[1].toInt() == 75 && bytes[2].toInt() == 3 && bytes[3].toInt() == 4) {
                        ...
                    } else {
                        inflate(bytes)?.let {
                            val movieEntity = MovieEntity.ADAPTER.decode(it)
                            ....
                        }
                    }
                } 
            } catch (e: java.lang.Exception) {
                this.invokeErrorCallback(e, callback)
            } finally {
                if (closeInputStream) {
                    inputStream.close()
                }
            }
        }
    }
}
```

下载了 svga源码，调试发现是`SvgaParser`里`decodeFromInputStream`时，`MovieEntity.ADAPTER.decode(byteArray)`报错。

当`if(bytes.size > 4 && bytes[0].toInt() == 80 && bytes[1].toInt() == 75 && bytes[2].toInt() == 3 && bytes[3].toInt() == 4) == false`时，才执行`MovieEntity.ADAPTER.decode`。就是说**svga 2.0**才会报这个错。

----

但是，我clone [wire-runtime:2.3.0-RC1](https://github.com/square/wire/tree/wire-2.3.0-RC1/wire-runtime)下来，让svga library依赖本地`wire-runtime`代码。调试发现我所有线上的svga资源，都不执行`skipGroup` T_T

所以暂时没找到重现方法，至少定位了问题。不是这个svga库的bug

----

## Svga 2.0文件出错吗？

我试过把svga2.0文件，改几个字节（用代码改），`inflate(bytes)`时已经报错，不可能执行`MovieEntity.ADAPTER.decode(bytes)`.

在后面追加字节，`MovieEntity.ADAPTER.decode(bytes)`正常执行-_-#

## 怀疑多线程引起

因为`MovieEntity.ADAPTER`是静态变量，会不会同时`decode(bytes)`就有问题呢？

```
public abstract class ProtoAdapter<E> {

  public abstract E decode(ProtoReader reader) throws IOException;

  public final E decode(byte[] bytes) throws IOException {
    checkNotNull(bytes, "bytes == null");
    return decode(new Buffer().write(bytes));
  }

  public final E decode(BufferedSource source) throws IOException {
    checkNotNull(source, "source == null");
    return decode(**new ProtoReader(source)**);
  }
}
```

```
private static final class ProtoAdapter_MovieEntity extends ProtoAdapter<MovieEntity> {
@Override
        public MovieEntity decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                ....
            }
            ....
        }
}
```

可以看到`ProtoAdapter_MovieEntity`继承`decode(ProtoReader reader)`，在父类`reader`是每次新建的：`new ProtoReader(new Buffer().write(bytes))`

**所以`reader.nextTag()`应该不存在多线程问题。**


----

只能让设计师把svga 2.0换1.0先，观察几天看看效果

**Comment by 569785819** [comment]
你这个解决了么，最近我遇到比较多这个报错
