### ISSUE TITLE
Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM

### ISSUE THREAD

**Issue by yinyangwu** [svga/SVGAPlayer-Android#278]
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM
       at java.util.AbstractList.iterator(AbstractList.java:569)
       at com.opensource.svgaplayer.entities.SVGAVideoSpriteEntity.<init>(SVGAVideoSpriteEntity.java:63)
       at com.opensource.svgaplayer.SVGAVideoEntity.resetSprites(SVGAVideoEntity.java:179)
       at com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.java:90)
       at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.java:170)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 7330 byte allocation with 6699 free bytes and 6KB until OOM
       at java.lang.String.<init>(String.java:233)
       at okio.Buffer.readString(Buffer.java:716)
       at okio.Buffer.readUtf8(Buffer.java:691)
       at com.squareup.wire.ProtoReader.readString(ProtoReader.java:267)
       at com.squareup.wire.ProtoAdapter$12.decode(ProtoAdapter.java:385)
       at com.squareup.wire.ProtoAdapter$12.decode(ProtoAdapter.java:375)
       at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.decode(FrameEntity.java:236)
       at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.decode(FrameEntity.java:202)
       at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.decode(SpriteEntity.java:181)
       at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.decode(SpriteEntity.java:153)
       at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:242)
       at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:206)
       at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:203)
       at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:185)
       at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.java:141)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by painld6** [comment]
请问用的是哪个版本，以及能否描述下使用场景？

**Comment by yinyangwu** [comment]
> 请问用的是哪个版本，以及能否描述下使用场景？

我使用的是最新版本，SVGA_VERSION=2.5.7，用户在进入我们的房间后，由于赠送礼物展示的特效显示的时候就报出这种崩溃，从Firebase Crashlytics上面复制过来的。
