### ISSUE TITLE
StackOverflowError: stack size 1041KB at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:1)

### ISSUE THREAD

**Issue by longkongjun** [svga/SVGAPlayer-Android#282]
at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:83)
at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:83)
at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:83)
at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:83)
at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:83)
at com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:83)

//请问这种情况有办法规避吗？

**Comment by longkongjun** [comment]
日志补充：    
    at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:9)
    at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:0)
    at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:10)
    at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:13)
    at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.java:101)

**Comment by kkmike999** [comment]
@longkongjun 你这个崩溃多吗？我也遇到  #273

**Comment by painld6** [comment]
目前我们这边无法复现，能否提供相关的 svga 文件给到我们测试下呢？

**Comment by Felix1030** [comment]
我这边也超级多这个崩溃

**Comment by Felix1030** [comment]
java.lang.StackOverflowError: 
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:217)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup
  at com.squareup.wire.ProtoReader.skipGroup
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.skipGroup (SourceFile:224)
  at com.squareup.wire.ProtoReader.nextTag (SourceFile:143)
  at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode (SourceFile:237)
  at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode (SourceFile:206)
  at com.squareup.wire.ProtoAdapter.decode (SourceFile:203)
  at com.squareup.wire.ProtoAdapter.decode (SourceFile:185)
  at com.opensource.svgaplayer.SVGAParser$i.run (SourceFile:366)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

**Comment by Felix1030** [comment]
作者能回复一下？

**Comment by MrRightDongYuJie1314** [comment]
我这边也遇到了同样的崩溃日志
java.lang.StackOverflowError
stack size 1040KB

com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)
com.squareup.wire.ProtoReader.skipGroup(ProtoReader.java:224)

**Comment by Felix1030** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
