### ISSUE TITLE
onComplete 回调前，已经remove 掉了SVGAImageView

### ISSUE THREAD

**Issue by HeroZ-Dodge** [svga/SVGAPlayer-Android#3]
Process: com.aipai.cloud, PID: 29992
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
                                                                     at com.opensource.svgaplayer.SVGAImageView$loadAttrs$$inlined$let$lambda$1$2.onComplete(SVGAImageView.kt:130)
                                                                     at com.opensource.svgaplayer.SVGAParser$parse$7$$special$$inlined$synchronized$lambda$1$1.run(SVGAParser.kt:142)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

估计是我在发起一个SVGAParser 任务，但是在onComplete完成前，我已经把这个SVGAImageView 从父布局中remove 掉了导致的

**Comment by PonyCui** [comment]
Provide demo please.
提供一个可以重现的 Demo 可以帮助我们快速解决问题。

**Comment by HeroZ-Dodge** [comment]
https://github.com/HeroZ-Dodge/SVGADemo

**Comment by HeroZ-Dodge** [comment]
https://github.com/HeroZ-Dodge/SVGADemo

**Comment by PonyCui** [comment]
已修正，先使用
```
compile 'com.github.yyued:SVGAPlayer-Android:c07409cbe2'
```
测试一下，没有问题，我会在下一个 release 中发布。
