### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by whoislxy** [svga/SVGAPlayer-Android#347]
使用版本：2.5.13

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM
       at com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.java:83)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
提前做缓存的时候直接粗暴的for循环调用导致，对此有什么好的建议么？队列？

**Comment by painld6** [comment]
建议按需解析，毕竟 SVGAParser 只是解析器

**Comment by whoislxy** [comment]
主要作预缓存，可以用的时候直接播放

**Comment by painld6** [comment]
> 主要作预缓存，可以用的时候直接播放

我明白你想的，只是如果简单粗暴直接 for 循环同时解析 10 多个 svga 文件或者更多，内存肯定撑不住

**Comment by shejishi** [comment]
有没有想过增加磁盘缓存或者内存缓存`library`

**Comment by painld6** [comment]
> 有没有想过增加磁盘缓存或者内存缓存`library`

会考虑，但 SVGAImageView 其功能就是播放和解析
