### ISSUE TITLE
新缓存模式，在清理缓存后会导致 java.lang.Error: java.io.IOException

### ISSUE THREAD

**Issue by Duosl** [svga/SVGAPlayer-Android#349]
# 新缓存模式，在清理缓存后会导致 java.lang.Error: java.io.IOException

## 复现步骤：
1. 进入一个onResume会重新解析SVGA（重新执行decodeXXX）的页面
2. 进入系统或APP提供的清理缓存功能，进行缓存清理
3. 回到步骤1所说的页面后，会发生崩溃

 **at com.opensource.svgaplayer.SVGAParser$_decodeFromInputStream$1$$special$$inlined$let$lambda$2.run(SVGAParser.kt:240)**

### 崩溃信息如下：
```
E/AndroidRuntime: FATAL EXCEPTION: SVGAParser-Thread-5
    java.lang.Error: java.io.IOException: No such file or directory
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at com.opensource.svgaplayer.SVGAParser$_decodeFromInputStream$1$$special$$inlined$let$lambda$2.run(SVGAParser.kt:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by Duosl** [comment]
@PonyCui 辛苦帮忙看一下这个问题

**Comment by painld6** [comment]
升级到 2.5.14 就行了，这个问题已经修复提过 pr 了#332

**Comment by Duosl** [comment]
> 升级到 2.5.14 就行了，这个问题已经修复提过 pr 了#332

@painld6  嗯嗯 辛苦了，我看了这个PR，有个疑问：这个能否在createNewFile之前进行父目录的检查，没有则创建父目录？只是单纯的catch一下，是不是不太好

**Comment by Duosl** [comment]
> 升级到 2.5.14 就行了，这个问题已经修复提过 pr 了#332

@painld6  嗯嗯 辛苦了，我看了这个PR。 有个疑问：这个能否在createNewFile之前进行父目录的检查，没有则创建父目录？只是单纯的catch一下，是不是不太好

**Comment by painld6** [comment]
> 嗯嗯 辛苦了，我看了这个PR，有个疑问：这个能否在createNewFile之前进行父目录的检查，没有则创建父目录？只是单纯的catch一下，是不是不太好

是的，因为当时还不清楚具体原因会导致崩溃，所以先加上 try-catch 避免崩溃发生

**Comment by Duosl** [comment]
> > 嗯嗯 辛苦了，我看了这个PR，有个疑问：这个能否在createNewFile之前进行父目录的检查，没有则创建父目录？只是单纯的catch一下，是不是不太好
> 
> 是的，因为当时还不清楚具体原因会导致崩溃，所以先加上 try-catch 避免崩溃发生

嗯 哈哈 那现在能否确定大概原因了呢？
我这边理解的就是在creatNewFile 的时候，父目录不存在导致的问题。辛苦帮忙看看能否增加一个判断父目录的逻辑吧 [抱拳]
@painld6

**Comment by painld6** [comment]
> > > 嗯嗯 辛苦了，我看了这个PR，有个疑问：这个能否在createNewFile之前进行父目录的检查，没有则创建父目录？只是单纯的catch一下，是不是不太好
> > 
> > 
> > 是的，因为当时还不清楚具体原因会导致崩溃，所以先加上 try-catch 避免崩溃发生
> 
> 嗯 哈哈 那现在能否确定大概原因了呢？
> 我这边理解的就是在creatNewFile 的时候，父目录不存在导致的问题。辛苦帮忙看看能否增加一个判断父目录的逻辑吧 [抱拳]

嗯嗯，可以的
