### ISSUE TITLE
可以把com.squareup.wire:wire-runtime版本升级一下么

### ISSUE THREAD

**Issue by chenzhongyu** [svga/SVGAPlayer-Android#372]
项目中接入了com.squareup.wire:wire-runtime:3.6.0，但是svga中的com.squareup.wire:wire-runtime版本太低，导致一加载assets中的svga文件，就崩溃了。
日志如下：
> 2021-07-08 15:54:07.041 23163-2105/com.example.ponycui_home.svgaplayer E/AndroidRuntime: FATAL EXCEPTION: SVGAParser-Thread-1
    Process: com.example.ponycui_home.svgaplayer, PID: 23163
    java.lang.NoSuchMethodError: No static method newEnumAdapter(Ljava/lang/Class;)Lcom/squareup/wire/RuntimeEnumAdapter; in class Lcom/squareup/wire/ProtoAdapter; or its super classes (declaration of 'com.squareup.wire.ProtoAdapter' appears in /data/app/~~X4jHt5psp_RWhv5WsTK8Nw==/com.example.ponycui_home.svgaplayer-LgBd5icBGvQnrGjuOnnaGA==/base.apk)
        at com.opensource.svgaplayer.proto.ShapeEntity$ShapeType.<clinit>(ShapeEntity.java:235)
        at com.opensource.svgaplayer.proto.ShapeEntity.<clinit>(ShapeEntity.java:26)
        at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.decode(FrameEntity.java:237)
        at com.opensource.svgaplayer.proto.FrameEntity$ProtoAdapter_FrameEntity.decode(FrameEntity.java:202)
        at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.decode(SpriteEntity.java:181)
        at com.opensource.svgaplayer.proto.SpriteEntity$ProtoAdapter_SpriteEntity.decode(SpriteEntity.java:153)
        at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:242)
        at com.opensource.svgaplayer.proto.MovieEntity$ProtoAdapter_MovieEntity.decode(MovieEntity.java:206)
        at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:321)
        at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:319)
        at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

> dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.github.svga:SVGAPlayer-Android:2.5.15'
    implementation 'com.squareup.wire:wire-runtime:3.6.0'
    implementation 'com.squareup.okhttp3:okhttp:3.4.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

**Comment by PonyCui** [comment]
建议你自行 fork 一下
