### ISSUE TITLE
svga解析失败可能是由于什么原因导致的？

### ISSUE THREAD

**Issue by tmexcept** [svga/SVGAPlayer-Android#377]
07-15 20:14:13.339 10545-10545  W/Log: parseSVGA  cartoonIcon=9625944e-3805-4a48-8ee5-45f06a9e3f70.svga   file.exists()=true
07-15 20:14:13.469 10545-10898  W/System.err: java.util.zip.DataFormatException: invalid code lengths set
07-15 20:14:13.469 10545-10898  W/System.err:     at java.util.zip.Inflater.inflateImpl(Native Method)
07-15 20:14:13.469 10545-10898  W/System.err:     at java.util.zip.Inflater.inflate(Inflater.java:237)
07-15 20:14:13.469 10545-10898  W/System.err:     at com.opensource.svgaplayer.SVGAParser.inflate(SVGAParser.kt:458)
07-15 20:14:13.469 10545-10898  W/System.err:     at com.opensource.svgaplayer.SVGAParser.access$inflate(SVGAParser.kt:27)
07-15 20:14:13.469 10545-10898  W/System.err:     at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:310)
07-15 20:14:13.469 10545-10898  W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-15 20:14:13.469 10545-10898  W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-15 20:14:13.469 10545-10898  W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-15 20:14:13.545 10545-10545 E/Log: SvgaUtils  parseSVGALocal  onError  /storage/sdcard0/xijing/resources/8c97e6df-c2f5-4476-989d-993aa5ab24e6.svga

07-15 20:14:13.687 10545-10898  W/System.err: java.util.zip.DataFormatException: invalid block type
07-15 20:14:13.687 10545-10898  W/System.err:     at java.util.zip.Inflater.inflateImpl(Native Method)
07-15 20:14:13.687 10545-10898  W/System.err:     at java.util.zip.Inflater.inflate(Inflater.java:237)
07-15 20:14:13.687 10545-10898  W/System.err:     at com.opensource.svgaplayer.SVGAParser.inflate(SVGAParser.kt:458)
07-15 20:14:13.687 10545-10898  W/System.err:     at com.opensource.svgaplayer.SVGAParser.access$inflate(SVGAParser.kt:27)
07-15 20:14:13.687 10545-10898  W/System.err:     at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:310)
07-15 20:14:13.687 10545-10898  W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-15 20:14:13.687 10545-10898  W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-15 20:14:13.687 10545-10898  W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-15 20:14:13.789 10545-10545 E/Log: SvgaUtils  parseSVGALocal  onError  /storage/sdcard0/xijing/resources/8c97e6df-c2f5-4476-989d-993aa5ab24e6.svga

偶现的问题，

**Comment by tmexcept** [comment]
implementation 'com.github.yyued:SVGAPlayer-Android:2.5.15'

**Comment by painld6** [comment]
看起来是像是解压大小不一致导致的问题，方便提供下 svga 文件吗？我这边尝试下

**Comment by tmexcept** [comment]
同一个svga文件，再次打开又能正常解析了，不是说这个文件一定解析不了，猜测不是svga文件的问题，是解析时机问题？还是有可能哪方面的问题？。
调用方法是
InputStream inputStream = new FileInputStream(file);
SVGAParser.decodeFromInputStream（）

解析已下载到本地的svga文件 偶现问题：
2021-07-16 19:56:27.341 25553-25553  W/Log: parseSVGA  cartoonIcon=9625944e-3805-4a48-8ee5-45f06a9e3f70.svga   file.exists()=true
2021-07-16 19:56:27.408 25553-26948  W/System.err: java.util.zip.DataFormatException: invalid stored block lengths
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at java.util.zip.Inflater.inflateBytes(Native Method)
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at java.util.zip.Inflater.inflate(Inflater.java:278)
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at com.opensource.svgaplayer.SVGAParser.inflate(SVGAParser.kt:458)
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at com.opensource.svgaplayer.SVGAParser.access$inflate(SVGAParser.kt:27)
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at com.opensource.svgaplayer.SVGAParser$decodeFromInputStream$1.run(SVGAParser.kt:310)
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-07-16 19:56:27.409 25553-26948  W/System.err:     at java.lang.Thread.run(Thread.java:923)

**Comment by painld6** [comment]
应该是解压的时候出现这个问题，顺便问下，你测试的时候是在 RecyclerView 这种滚动的布局中尝试的吗？

**Comment by tmexcept** [comment]
不是滚动布局，父布局是ConstraintLayout

**Comment by painld6** [comment]
已经更新到 2.6.1 了，试下看看还有没有这种情况
