### ISSUE TITLE
加载这张图片会造成OOM,然后整个页面会卡住,有什么办法处理吗?

### ISSUE THREAD

**Issue by clbDream** [svga/SVGAPlayer-Android#412]
https://bbyy0108.oss-cn-shanghai.aliyuncs.com/gift/svga/%E4%B8%96%E7%BA%AA%E5%A9%9A%E7%A4%BC.svga

2022-03-14 14:44:55.778 28305-30042/com.yy.mobile.svga.glideplugin.demo E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.yy.mobile.svga.glideplugin.demo, PID: 28305
    java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 39464 free bytes and 38KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 86507520 bytes)
        at com.opensource.svgaplayer.SVGAVideoSpriteFrameEntity.<init>(SVGAVideoSpriteFrameEntity.kt:99)
        at com.opensource.svgaplayer.SVGAVideoSpriteEntity.<init>(SVGAVideoSpriteEntity.kt:40)
        at com.opensource.svgaplayer.SVGAVideoEntity.resetSprites(SVGAVideoEntity.kt:125)
        at com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.kt:61)
        at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:182)
        at com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:25)
        at com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:95)
        at com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:25)
        at com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.kt:61)
        at java.lang.Thread.run(Thread.java:923)

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Android/issues/408
