### ISSUE TITLE
Android Studio Dolphin can not preview

### ISSUE THREAD

**Issue by simplepeng** [svga/SVGAPlayer-Android#448]
```java
java.lang.IllegalStateException: context.cacheDir must not be null
	at com.opensource.svgaplayer.SVGACache.onCreate(SVGACache.kt:39)
	at com.opensource.svgaplayer.SVGACache.onCreate(SVGACache.kt:33)
	at com.opensource.svgaplayer.SVGAParser.<init>(SVGAParser.kt:29)
	at com.opensource.svgaplayer.SVGAImageView.parserSource(SVGAImageView.kt:94)
	at com.opensource.svgaplayer.SVGAImageView.loadAttrs(SVGAImageView.kt:87)
	at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:63)
	at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt:24)
	at com.opensource.svgaplayer.SVGAImageView.<init>(SVGAImageView.kt)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Moonwing2020** [comment]
have you work it out?

**Comment by sergiofdomingues** [comment]
My AS Dolphin won't show preview either....

**Comment by appcoderandroid2** [comment]
Have anyone got the solution? I am also stuck in the same issue

**Comment by tankai2525** [comment]
Me too, I don't know what to do

The following classes could not be instantiated:
- com.opensource.svgaplayer.SVGAImageView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.

**Comment by W-quan** [comment]
+1
