### ISSUE TITLE
严格模式抓到资源未回收的提示

### ISSUE THREAD

**Issue by IceDcap** [svga/SVGAPlayer-Android#48]
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                         java.lang.Throwable: Explicit termination method 'end' not called
                                                             at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                             at java.util.zip.Inflater.<init>(Inflater.java:104)
                                                             at java.util.zip.Inflater.<init>(Inflater.java:111)
                                                             at com.opensource.svgaplayer.SVGAParser.inflate(SVGAParser.kt:265)
                                                             at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:174)
                                                             at com.opensource.svgaplayer.SVGAParser$pars

**Comment by PonyCui** [comment]
Fixed on 2.1.3 version
