### ISSUE TITLE
Crash when play animation

### ISSUE THREAD

**Issue by onecoders** [svga/SVGAPlayer-Android#6]
E/MtaSDK: java.lang.OutOfMemoryError: Failed to allocate a 4002012 byte allocation with 2277808 free bytes and 2MB until OOM
                                                              at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                              at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
                                                              at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:533)
                                                              at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:556)
                                                              at com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:80)
                                                              at com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.kt:54)
                                                              at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:169)
                                                              at com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:23)
                                                              at com.opensource.svgaplayer.SVGAParser$parse$5.run(SVGAParser.kt:96)
                                                              at java.lang.Thread.run(Thread.java:761)

**Comment by PonyCui** [comment]
Please send your svga file to help@svga.io

**Comment by onecoders** [comment]
Sent already

**Comment by PonyCui** [comment]
Too much large width * height size PNGs.
Every PNG is 750 * 1334, that's not fine.
Please ask your designer, make each png as small as possible.

**Comment by onecoders** [comment]
ok,I will,thanks
