### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by allen1988** [svga/SVGAPlayer-Android#88]
## java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:122)
	at com.opensource.svgaplayer.f.a(SVGAParser.kt:278)
	at com.opensource.svgaplayer.f.a(SVGAParser.kt:174)
	at com.opensource.svgaplayer.f.a(SVGAParser.kt:25)
	at com.opensource.svgaplayer.f$f.run(SVGAParser.kt:104)
	at java.lang.Thread.run(Thread.java:841)

**Comment by allen1988** [comment]
you must resolve it
