### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by boatt** [svga/SVGAPlayer-Android#92]
锤子T1

 Process: com.example.zhoutao.svgdemo, PID: 16130
    java.lang.NoClassDefFoundError: com.opensource.svgaplayer.SVGAVideoEntity$resetAudios$2$3
        at com.opensource.svgaplayer.SVGAVideoEntity.resetAudios(SVGAVideoEntity.kt:178)
        at com.opensource.svgaplayer.SVGAVideoEntity.prepare$giftLibrary_debug(SVGAVideoEntity.kt:79)
        at com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:96)
        at com.opensource.svgaplayer.SVGAParser$parse$3.invoke(SVGAParser.kt:25)
        at com.opensource.svgaplayer.SVGAParser$FileDownloader$resume$1.run(SVGAParser.kt:61)
        at java.lang.Thread.run(Thread.java:818)

**Comment by PonyCui** [comment]
Please provide a demo project reproduce issue.
If this issue shows on specific device, we will resolve it slower.

**Comment by MadisonRong** [comment]
I got the same exception in my App when using 2.3.0. Due to business reason, can not share the code to you, and the device that recurrent this problem is Redmi 4A.
Device: Redmi 4A
MIUI version: MIUI 8.5 stable
Android version: 6.0.1 
memory: 2GB

Most of our test devices is running good with this version player.This is a special one as far as we found.

**Comment by MadisonRong** [comment]
It fixed in 2.4.2. Thank you so much
