### ISSUE TITLE
parse  OOM

### ISSUE THREAD

**Issue by jhyHenry** [svga/SVGAPlayer-Android#95]
I have a crash：if there are too many resouce to parsed,it will crash.

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
	at java.lang.Thread.nativeCreate(Thread.java)
	at java.lang.Thread.start(Thread.java:753)
	at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.java:115)
	at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.java:76)

**Comment by PonyCui** [comment]
@YvesCheung thank you for your comment, we should provide a ThreadPool options for developer. Thank you very much.

**Comment by jhyHenry** [comment]
3Q
