### ISSUE TITLE
oom

### ISSUE THREAD

**Issue by zivxia** [svga/SVGAPlayer-Android#98]
java.lang.OutOfMemoryError: Failed to allocate a 1399378 byte allocation with 925568 free bytes and 903KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:537)
at com.opensource.svgaplayer.SVGAVideoEntity.resetImages(SVGAVideoEntity.kt:114)
at com.opensource.svgaplayer.SVGAVideoEntity.<init>(SVGAVideoEntity.kt:70)
at com.opensource.svgaplayer.SVGAParser.parse(SVGAParser.kt:185)
at com.opensource.svgaplayer.SVGAParser.access$parse(SVGAParser.kt:25)
at com.opensource.svgaplayer.SVGAParser$parse$5.run(SVGAParser.kt:110)
at java.lang.Thread.run(Thread.java:760)

**Comment by MrHurricaner** [comment]
[](url)

**Comment by PonyCui** [comment]
Your svga file contains large images, optimize it.
